# Documentation: https://docs.travis-ci.com/user/languages/julia/
language: julia

# Use Julia 1.5 + whatever the latest stable release is
julia:
  - 1.5
  - 1

# Only test on Linux for now
os:
  - linux
  # - osx

# Disable email notifications
notifications:
  email: false

# Build package verbosely and run tests with coverage enabled
script:
  - julia --color=yes --project=. -e "import Pkg; Pkg.build(verbose=true)"
  - julia --color=yes --project=. -e "import Pkg; Pkg.test(coverage=true)"

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

# Enable coverage reported by Coverage.io and Coveralls.io
# Note: Although documented as such, it does not seem to work with just these two lines!?!
# codecov: true
# coveralls: true

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
    #  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
